// <auto-generated />
using Dawstin_CPW221_BaseballShop.Baseball_Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Dawstin_CPW221_BaseballShop.Migrations
{
    [DbContext(typeof(BaseballShop)), Migration("20250514130547_Initial")]
    internal class InitialBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dawstin_CPW221_BaseballShop.Models.Product", b =>
            {
                b.Property<int>("ProductID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(10,2)");

                b.Property<int>("CategoryID")
                    .HasColumnType("int");

                b.HasKey("ProductID");

                b.ToTable("Products");
            });

            modelBuilder.Entity("Dawstin_CPW221_BaseballShop.Models.Order", b =>
            {
                b.Property<int>("OrderID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                b.Property<string>("CustomerName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("TotalPrice")
                    .HasColumnType("decimal(10,2)");

                b.Property<string>("Status")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("OrderID");

                b.ToTable("Orders");
            });
#pragma warning restore 612, 618
        }
    }
}